import type { DemoDataset } from "./types";

// The Hollis family of Stephenville, Texas — our flagship demo. Built to feel
// like a real rodeo family: women & girls at the center, horses treated as
// athletes, a season already in motion (spring 2026 results feeding summer
// qualifying ladders).
export const demoData: DemoDataset = {
  family: {
    id: "fam_hollis",
    name: "The Hollis Family",
    homeTown: "Stephenville",
    state: "TX",
    plan: "Arena Pro",
    motto: "Feed before sunrise. Ride like it's the last eight seconds.",
  },

  contestants: [
    {
      id: "c_rylee",
      familyId: "fam_hollis",
      firstName: "Rylee",
      lastName: "Hollis",
      age: 16,
      division: "Senior",
      associations: ["NHSRA", "NLBRA"],
      disciplines: ["Barrel Racing", "Breakaway Roping"],
      avatarSeed: "rylee-barrels",
      backNumber: "117",
      bio: "Junior at Stephenville High. Runs Dolly in the 1D and ropes calves before homework. Chasing a state finals barrel spot and her first NLBRA Top Hand season.",
    },
    {
      id: "c_cade",
      familyId: "fam_hollis",
      firstName: "Cade",
      lastName: "Hollis",
      age: 13,
      division: "Junior",
      associations: ["NJHRA"],
      disciplines: ["Tie-Down Roping", "Team Roping"],
      avatarSeed: "cade-roper",
      backNumber: "44",
      bio: "Seventh grader who heels for his buddy and ties down on Chex. Up at 5 to feed, last one to leave the practice pen.",
    },
    {
      id: "c_sissy",
      familyId: "fam_hollis",
      firstName: "Maelaina",
      lastName: "Hollis",
      age: 8,
      division: "Pee Wee",
      associations: ["NLBRA"],
      disciplines: ["Barrel Racing", "Goat Tying", "Dummy Roping"],
      avatarSeed: "sissy-peewee",
      backNumber: "8",
      bio: "Runs Peanut as fast as his little legs go. Collects every participation ribbon like a gold buckle.",
    },
  ],

  horses: [
    {
      id: "h_dolly",
      familyId: "fam_hollis",
      name: "Famous Dolly Whiz",
      barnName: "Dolly",
      breed: "Quarter Horse",
      age: 9,
      color: "Sorrel",
      bloodlines: "Frenchmans Guy × Dash Ta Fame",
      role: "Barrel mare — Rylee's 1D horse",
      trainer: "Kasey Worrell",
      riderId: "c_rylee",
      farrierDueDays: 9,
      vetDueDays: 41,
      vaccinationsCurrent: true,
      insured: true,
      notes: "Loves deep ground. Gets strong on the first barrel — keep her gathered.",
      record: "2D average winner, 3 county wins in 2026",
    },
    {
      id: "h_boomer",
      familyId: "fam_hollis",
      name: "Boomer's Last Call",
      barnName: "Boomer",
      breed: "Quarter Horse",
      age: 12,
      color: "Bay",
      bloodlines: "Metallic Cat lineage",
      role: "Breakaway / score horse — Rylee",
      trainer: "Self",
      riderId: "c_rylee",
      farrierDueDays: 22,
      vetDueDays: 12,
      vaccinationsCurrent: true,
      insured: true,
      notes: "Scores honest. Watch the left front — slight heat after the Glen Rose run.",
      record: "Solid 2.4–2.9 breakaway times",
    },
    {
      id: "h_chex",
      familyId: "fam_hollis",
      name: "Smart Little Chex",
      barnName: "Chex",
      breed: "Quarter Horse",
      age: 10,
      color: "Buckskin",
      bloodlines: "Smart Little Lena",
      role: "Tie-down / heel horse — Cade",
      trainer: "Self",
      riderId: "c_cade",
      farrierDueDays: 3,
      vetDueDays: 60,
      vaccinationsCurrent: false,
      insured: false,
      notes: "Coggins expires before State — book the vet. Works a rope like a clock.",
      record: "Junior tie-down, two seconds at district",
    },
    {
      id: "h_peanut",
      familyId: "fam_hollis",
      name: "Mr. Peanut",
      barnName: "Peanut",
      breed: "POA Pony",
      age: 15,
      color: "Palomino",
      bloodlines: "Grade pony, heart of gold",
      role: "Pee Wee everything — Maelaina",
      trainer: "Family",
      riderId: "c_sissy",
      farrierDueDays: 17,
      vetDueDays: 88,
      vaccinationsCurrent: true,
      insured: false,
      notes: "Babysitter. Will pack anybody. Bombproof at the gate.",
      record: "Undefeated in hearts",
    },
  ],

  events: [
    {
      id: "e1",
      name: "Cross Timbers Youth Rodeo — Series #6",
      association: "NLBRA",
      disciplines: ["Barrel Racing", "Breakaway Roping", "Goat Tying", "Dummy Roping"],
      divisions: ["Pee Wee", "Junior", "Senior"],
      venue: "Erath County Arena",
      city: "Stephenville",
      state: "TX",
      startDate: "2026-06-06",
      endDate: "2026-06-07",
      entryDeadline: "2026-06-03",
      drawPosted: false,
      feePerEvent: 35,
      status: "closing-soon",
      added: true,
    },
    {
      id: "e2",
      name: "NHSRA Texas State Finals",
      association: "NHSRA",
      disciplines: ["Barrel Racing", "Breakaway Roping", "Tie-Down Roping", "Team Roping"],
      divisions: ["Senior"],
      venue: "Will Rogers Memorial Center",
      city: "Fort Worth",
      state: "TX",
      startDate: "2026-06-13",
      endDate: "2026-06-20",
      entryDeadline: "2026-06-01",
      drawPosted: false,
      feePerEvent: 65,
      status: "closing-soon",
      added: true,
    },
    {
      id: "e3",
      name: "Lone Star Junior Jackpot",
      association: "NJHRA",
      disciplines: ["Tie-Down Roping", "Team Roping", "Barrel Racing"],
      divisions: ["Junior"],
      venue: "Bosque County Expo",
      city: "Clifton",
      state: "TX",
      startDate: "2026-06-21",
      endDate: "2026-06-21",
      entryDeadline: "2026-06-18",
      drawPosted: false,
      feePerEvent: 40,
      status: "open",
      added: true,
    },
    {
      id: "e4",
      name: "Red River Breakaway Classic",
      association: "AJRA",
      disciplines: ["Breakaway Roping"],
      divisions: ["Junior", "Senior"],
      venue: "Love County Fairgrounds",
      city: "Marietta",
      state: "OK",
      startDate: "2026-07-04",
      endDate: "2026-07-05",
      entryDeadline: "2026-06-28",
      drawPosted: false,
      feePerEvent: 50,
      status: "open",
      added: false,
    },
    {
      id: "e5",
      name: "National Little Britches Finals (NLBFR)",
      association: "NLBRA",
      disciplines: ["Barrel Racing", "Breakaway Roping", "Goat Tying"],
      divisions: ["Pee Wee", "Junior", "Senior"],
      venue: "Lazy E Arena",
      city: "Guthrie",
      state: "OK",
      startDate: "2026-07-19",
      endDate: "2026-07-25",
      entryDeadline: "2026-07-01",
      drawPosted: false,
      feePerEvent: 55,
      status: "open",
      added: false,
    },
    {
      id: "e6",
      name: "Glen Rose Spring Series — Finals",
      association: "NLBRA",
      disciplines: ["Barrel Racing", "Breakaway Roping", "Goat Tying"],
      divisions: ["Pee Wee", "Junior", "Senior"],
      venue: "Somervell County Expo",
      city: "Glen Rose",
      state: "TX",
      startDate: "2026-05-23",
      endDate: "2026-05-24",
      entryDeadline: "2026-05-20",
      drawPosted: true,
      feePerEvent: 35,
      status: "drawn",
      added: true,
    },
  ],

  runs: [
    {
      id: "r1",
      contestantId: "c_rylee",
      horseId: "h_dolly",
      eventName: "Glen Rose Spring Series — Finals",
      discipline: "Barrel Racing",
      date: "2026-05-24",
      result: "14.812",
      placing: 1,
      points: 10,
      footing: "Deep, freshly worked",
      notes: "Best home pattern of the year. Dolly hunted every barrel.",
    },
    {
      id: "r2",
      contestantId: "c_rylee",
      horseId: "h_boomer",
      eventName: "Glen Rose Spring Series — Finals",
      discipline: "Breakaway Roping",
      date: "2026-05-24",
      result: "2.61",
      placing: 3,
      points: 6,
      footing: "Firm",
      notes: "Clean catch, slow to throw slack. Boomer left front warm after.",
    },
    {
      id: "r3",
      contestantId: "c_rylee",
      horseId: "h_dolly",
      eventName: "Cross Timbers Series #5",
      discipline: "Barrel Racing",
      date: "2026-05-09",
      result: "15.004",
      placing: 2,
      points: 8,
      footing: "Slick on the back side",
      notes: "Tipped nothing. Lost time leaving the third.",
    },
    {
      id: "r4",
      contestantId: "c_cade",
      horseId: "h_chex",
      eventName: "Lone Star Junior Jackpot #4",
      discipline: "Tie-Down Roping",
      date: "2026-05-17",
      result: "11.9",
      placing: 2,
      points: 8,
      footing: "Good",
      notes: "Great corner, fumbled the tie. Chex was money.",
    },
    {
      id: "r5",
      contestantId: "c_sissy",
      horseId: "h_peanut",
      eventName: "Glen Rose Spring Series — Finals",
      discipline: "Barrel Racing",
      date: "2026-05-24",
      result: "19.430",
      placing: 4,
      points: 4,
      footing: "Deep",
      notes: "Smiled the whole pattern. Stayed in the saddle on the turn!",
    },
    {
      id: "r6",
      contestantId: "c_rylee",
      horseId: "h_dolly",
      eventName: "Cross Timbers Series #4",
      discipline: "Barrel Racing",
      date: "2026-04-25",
      result: "14.939",
      placing: 1,
      points: 10,
      footing: "Worked twice",
      notes: "Won the 1D. Money run.",
    },
  ],

  ladders: [
    {
      id: "l1",
      contestantId: "c_rylee",
      pathway: "NHSRA",
      discipline: "Barrel Racing",
      title: "Road to State Finals — Barrels",
      currentPoints: 248,
      targetPoints: 300,
      standing: "3rd in District 9",
      status: "on-track",
      nextDeadline: "2026-06-01",
      nextDeadlineLabel: "State entry closes",
      stages: [
        { label: "District Rodeos", state: "done", detail: "8 of 10 counted" },
        { label: "District Finals", state: "current", detail: "3rd — top 4 advance" },
        { label: "State Finals", state: "upcoming", detail: "Fort Worth, Jun 13" },
        { label: "Nationals (NHSFR)", state: "upcoming", detail: "Rock Springs, WY" },
      ],
    },
    {
      id: "l2",
      contestantId: "c_rylee",
      pathway: "NLBRA",
      discipline: "Breakaway Roping",
      title: "Top Hand Team — Breakaway",
      currentPoints: 3,
      targetPoints: 5,
      standing: "3 of 5 firsts",
      status: "at-risk",
      nextDeadline: "2026-07-01",
      nextDeadlineLabel: "NLBFR entry closes",
      stages: [
        { label: "Franchise Rodeos", state: "done", detail: "11 entered" },
        { label: "Top Hand Points", state: "current", detail: "3 of 5 first-place finishes" },
        { label: "NLBFR — Guthrie", state: "upcoming", detail: "Jul 19–25" },
      ],
    },
    {
      id: "l3",
      contestantId: "c_cade",
      pathway: "NJHRA",
      discipline: "Tie-Down Roping",
      title: "Road to State — Tie-Down",
      currentPoints: 162,
      targetPoints: 220,
      standing: "6th in district",
      status: "watch",
      nextDeadline: "2026-06-18",
      nextDeadlineLabel: "Need 2 strong jackpots",
      stages: [
        { label: "District Rodeos", state: "current", detail: "6th — top 4 advance" },
        { label: "District Finals", state: "upcoming", detail: "Two events left" },
        { label: "State Finals", state: "upcoming", detail: "Abilene, TX" },
      ],
    },
  ],

  sponsors: [
    {
      id: "s1",
      contestantId: "c_rylee",
      brand: "Lone Star Feed & Supply",
      category: "Feed store",
      tier: "Gold",
      annualValue: 2400,
      status: "active",
      renewalDate: "2026-12-01",
      deliverablesDone: 4,
      deliverablesTotal: 6,
    },
    {
      id: "s2",
      contestantId: "c_rylee",
      brand: "Bar-H Saddlery",
      category: "Tack & leather",
      tier: "Silver",
      annualValue: 1200,
      status: "renewal-due",
      renewalDate: "2026-06-15",
      deliverablesDone: 5,
      deliverablesTotal: 5,
    },
    {
      id: "s3",
      contestantId: "c_cade",
      brand: "Cross Timbers Vet Clinic",
      category: "Veterinary",
      tier: "Bronze",
      annualValue: 600,
      status: "pending",
      renewalDate: "2026-08-01",
      deliverablesDone: 1,
      deliverablesTotal: 4,
    },
  ],

  arenas: [
    {
      id: "a1",
      name: "Erath County Arena",
      city: "Stephenville",
      state: "TX",
      status: "safe",
      yearsActive: 47,
      threat: "Stable — community-owned",
      story:
        "Home ground. The Hollis kids took their first laps here. A model for what a protected arena looks like.",
      signatures: 0,
      signatureGoal: 0,
      economicImpact: 1_900_000,
      supporters: 312,
    },
    {
      id: "a2",
      name: "Sand Springs Rodeo Arena",
      city: "Sand Springs",
      state: "OK",
      status: "saved",
      yearsActive: 60,
      threat: "City council voted to close (2017) — community fought back and won",
      story:
        "Residents launched a petition and packed the council chambers. Proof that organized families can keep an arena open.",
      signatures: 4200,
      signatureGoal: 4000,
      economicImpact: 850_000,
      supporters: 1180,
    },
    {
      id: "a3",
      name: "Jackson Hole Rodeo Grounds",
      city: "Jackson",
      state: "WY",
      status: "threatened",
      yearsActive: 80,
      threat: "Rezoning for housing ahead of a 2026 lease expiration",
      story:
        "A grassroots 'Save the Rodeo Grounds' campaign gathered 1,300+ signatures. The fight is live and needs every voice.",
      signatures: 1340,
      signatureGoal: 5000,
      economicImpact: 3_400_000,
      supporters: 920,
    },
    {
      id: "a4",
      name: "South Tippecanoe Rodeo & Concert Venue",
      city: "Lafayette",
      state: "IN",
      status: "threatened",
      yearsActive: 4,
      threat: "Shut down over noise complaints and a zoning denial",
      story:
        "A family-owned venue silenced before it found its footing. Documenting its economic impact is the first step to reopening.",
      signatures: 610,
      signatureGoal: 3000,
      economicImpact: 420_000,
      supporters: 230,
    },
  ],

  budget: [
    { category: "Entry fees", spent: 3140, budget: 6000 },
    { category: "Horse care", spent: 7820, budget: 12000 },
    { category: "Travel & fuel", spent: 4310, budget: 8000 },
    { category: "Gear & tack", spent: 1960, budget: 3000 },
    { category: "Memberships", spent: 540, budget: 700 },
  ],

  season: {
    spend: 17_770,
    eventsEntered: 23,
    milesTraveled: 6_840,
    buckles: 4,
  },
};
