import type { Context } from "hono";
import type { Env } from "./index";

// Background music for the demo video, generated by Workers AI (minimax/music-2.6)
// and cached in R2. Instrumental Americana/country to match the rodeo voice.
// Order of precedence: R2 cache -> committed static asset -> AI generation.
// Returns 204 if none of those yield audio, so the video plays fine silent.

const VERSION = "1";
const KEY = `audio/tour-music-v${VERSION}.mp3`;
const PROMPT =
  "Warm instrumental country Americana: gentle fingerpicked acoustic guitar, soft pedal steel, light brushed drums and upright bass, hopeful and heartfelt, wide open Western feeling, mid-tempo, no vocals.";

export async function musicStatus(c: Context<{ Bindings: Env }>): Promise<Response> {
  if (c.env.MEDIA && (await c.env.MEDIA.head(KEY).catch(() => null))) {
    return c.json({ available: true });
  }
  const origin = new URL(c.req.url).origin;
  const head = await c.env.ASSETS.fetch(
    new Request(`${origin}/audio/tour-music.mp3`, { method: "HEAD" }),
  ).catch(() => null);
  // AI can generate on first play, so report available whenever we have the binding.
  return c.json({ available: !!head?.ok || !!c.env.AI });
}

export async function music(c: Context<{ Bindings: Env }>): Promise<Response> {
  const cache = caches.default;
  const cacheKey = new Request(new URL(c.req.url).toString());
  const hit = await cache.match(cacheKey);
  if (hit) return hit;

  const serve = (body: BodyInit) => {
    const resp = new Response(body, {
      headers: { "Content-Type": "audio/mpeg", "Cache-Control": "public, max-age=31536000" },
    });
    c.executionCtx.waitUntil(cache.put(cacheKey, resp.clone()));
    return resp;
  };

  // 1) R2 cache (persists across deploys).
  if (c.env.MEDIA) {
    const obj = await c.env.MEDIA.get(KEY).catch(() => null);
    if (obj) return serve(obj.body);
  }

  // 2) Committed static fallback.
  const origin = new URL(c.req.url).origin;
  const asset = await c.env.ASSETS.fetch(new Request(`${origin}/audio/tour-music.mp3`)).catch(() => null);
  if (asset?.ok) return serve(asset.body!);

  // 3) Generate with Workers AI, store in R2.
  if (c.env.AI) {
    const debug = c.req.query("debug") === "1";
    try {
      const out = (await c.env.AI.run("minimax/music-2.6", {
        is_instrumental: true,
        lyrics_optimizer: false,
        prompt: PROMPT,
        format: "mp3",
        sample_rate: 44100,
      } as Record<string, unknown>)) as { audio?: string };

      let bytes: Uint8Array | null = null;
      if (out?.audio?.startsWith("http")) {
        const r = await fetch(out.audio);
        if (r.ok) bytes = new Uint8Array(await r.arrayBuffer());
      } else if (out?.audio) {
        bytes = Uint8Array.from(atob(out.audio), (ch) => ch.charCodeAt(0));
      }

      if (debug) {
        return c.json({
          ok: !!bytes,
          bytes: bytes?.byteLength ?? 0,
          audioField: out?.audio ? out.audio.slice(0, 80) : null,
          keys: Object.keys(out ?? {}),
        });
      }

      if (bytes && bytes.byteLength > 1024) {
        if (c.env.MEDIA) {
          c.executionCtx.waitUntil(
            c.env.MEDIA.put(KEY, bytes, { httpMetadata: { contentType: "audio/mpeg" } }).then(() => undefined),
          );
        }
        return serve(bytes);
      }
    } catch (err) {
      if (debug) return c.json({ ok: false, error: String(err) }, 500);
      console.error("music generation failed", err);
    }
  }

  return new Response(null, { status: 204 });
}
